name             'bz_uwsgi'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures bz_uwsgi'
long_description 'Installs/Configures bz_uwsgi'
version          '0.1.0'

depends 'apt'
depends 'build-essential'
