name             'bz_uwsgi'
maintainer       'Brandon Zitzman'
maintainer_email 'brandon.zitzman1@gmail.com'
license          'all_rights'
description      'Custom Resource for installing uwsgi core'
long_description ''
version          '0.1.0'

depends 'apt'
depends 'build-essential'
